// GENERATED BY AMBORAS — do not edit manually
// Generated: 2026-07-05T07:36:21.561Z
// Class A plugins: ga4

import type { PluginRegistry } from '../../types/plugins'
import { GA4Provider as ga4_GA4Provider } from "@amboras-dev/ga4/slot-components"
import { GA4ViewItem as ga4_GA4ViewItem } from "@amboras-dev/ga4/slot-components"
import { GA4ViewItemList as ga4_GA4ViewItemList } from "@amboras-dev/ga4/slot-components"
import { GA4Search as ga4_GA4Search } from "@amboras-dev/ga4/slot-components"
import { GA4CartDelta as ga4_GA4CartDelta } from "@amboras-dev/ga4/slot-components"
import { GA4ViewCart as ga4_GA4ViewCart } from "@amboras-dev/ga4/slot-components"
import { GA4BeginCheckout as ga4_GA4BeginCheckout } from "@amboras-dev/ga4/slot-components"
import { GA4AddPaymentInfo as ga4_GA4AddPaymentInfo } from "@amboras-dev/ga4/slot-components"
import { GA4Purchase as ga4_GA4Purchase } from "@amboras-dev/ga4/slot-components"
import { GA4Identify as ga4_GA4Identify } from "@amboras-dev/ga4/slot-components"

export const PLUGIN_REGISTRY: PluginRegistry = {
  head: [],
  bodyEnd: [],
  rootProviders: [{ id: 'ga4', Component: ga4_GA4Provider, propsFromConfig: {"debugMode":"debug_mode","measurementId":"measurement_id"} }],
  homeHero: [],
  homeBelowFeatured: [],
  pdpAfterTitle: [],
  pdpBeforePrice: [],
  pdpBelowAddToCart: [],
  pdpTrustSignals: [],
  pdpAfterDescription: [],
  pdpTab: [],
  pdpAnalytics: [{ id: 'ga4', Component: ga4_GA4ViewItem, propsFromContext: ["productId","productHandle","productTitle","price","currency","sku","variantId","productCategory","productBrand"] }],
  collectionAboveGrid: [],
  collectionCard: [],
  collectionBelowGrid: [{ id: 'ga4', Component: ga4_GA4ViewItemList, propsFromContext: ["listId","listName","items"] }],
  cartDrawerFooter: [{ id: 'ga4', Component: ga4_GA4ViewCart, propsFromContext: ["cartId","itemCount","total"] }],
  cartUpdate: [{ id: 'ga4', Component: ga4_GA4CartDelta, propsFromContext: ["cartId","itemCount","total"] }],
  checkoutOrderSummary: [{ id: 'ga4', Component: ga4_GA4AddPaymentInfo, propsFromContext: ["cartId","total"] }],
  checkoutStart: [{ id: 'ga4', Component: ga4_GA4BeginCheckout, propsFromContext: ["cartId","total","currency","items"] }],
  checkoutComplete: [{ id: 'ga4', Component: ga4_GA4Purchase, propsFromContext: ["orderId","total","tax","shipping","currency","items","coupon"] }],
  searchAboveResults: [{ id: 'ga4', Component: ga4_GA4Search, propsFromContext: ["query"] }],
  accountOverview: [],
  account: [{ id: 'ga4', Component: ga4_GA4Identify, propsFromContext: ["customerId"] }],
  authSignup: [],
}